version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_KMAT_ExtProj_Feb18Project
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb18_ExtGIT_SF_Basic_ConnA
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb18_ExtGIT_SF_Basic_ConnB
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.integrations:Feb18_ExtGIT_SF_QueryCRM
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:Cust_ExtGIT_QueryCRMAccounts
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? iscloudstreamsconnectorservice.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_ExtGIT_QueryCRMAccounts.connectionAlias
  : project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb18_ExtGIT_SF_Basic_ConnB
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.poolable
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.poolable
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cr.username
  : bmk@softwareag.com
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cr.username
  : bmk@softwareag.com
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cr.password
  : "{AES}3gGMEiayJzoUBK1zn+MHSxnXxD1sVA/AUOaMrywz+PNqr29UZEbOgqP7UDJNCgdM"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cr.password
  : "{AES}sWAtkQNunCAyhB94bvFzyp9cJqx/ybSKaf0MRUDUzpjg4lZ6ErmHz4Q/hyPOt14G"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.connectionEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.socketLinger
  : "-1"
  ? iscloudstreamsconnectorservice.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_ExtGIT_QueryCRMAccounts.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.timeoutType
  : fixed
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.timeoutType
  : fixed
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnA.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:Feb18_ExtGIT_SF_Basic_ConnB.pr.useChunking
  : "false"
