version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_KMAT_ExtProj_Feb18Project
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:feb21_sf_extgit_connA
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:Cust_ExtGIT_QueryCRMAccounts
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.integrations:Feb18_ExtGIT_SF_QueryCRM
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.integrations:lakr_21feb
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:feb21_action
  packages:
  - name: Man_KMAT_ExtProj_Feb18Project
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? iscloudstreamsconnectorservice.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:feb21_action.connectionAlias
  : project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:feb21_sf_extgit_connA
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.retryCount
  : "3"
  ? iscloudstreamsconnectorservice.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_ExtGIT_QueryCRMAccounts.connectionAlias
  : project.man_kmat_extproj_feb18.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:Feb18_ExtGIT_SF_Basic_ConnB
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.poolable
  : "true"
  ? iscloudstreamsconnectorservice.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:feb21_action.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cr.username
  : cloudstreamssf@gmail.com
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cr.password
  : "{AES}8sR4eB5091OTFwzdoM1AY/hw2JgHVtvgKlgblnCFoeLf3EpEEjeRYDFewlk6Bpq6"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.socketStaleCheck
  : "true"
  ? iscloudstreamsconnectorservice.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Cust_ExtGIT_QueryCRMAccounts.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.timeoutType
  : fixed
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..man_kmat_extproj_feb18..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:feb21_sf_extgit_connA.startupRetryCount
  : "0"
